Html forms - Chris Tran
tran-christopher/c1023-code-solutions pull request #23
Opened 2023-10-31 15:19 UTC by tran-christopher

https://github.com/tran-christopher/c1023-code-solutions/assets/145728509/fec3db52-ffeb-4d84-bcb2-5b0a2ad83358

2023-10-31 16:43 UTC, shawnkost requested changes
Couple changes here Chris!

2023-10-31 16:43 UTC, shawnkost commented on html-forms/index.html
> +    </p>
All of this needs to be wrapped inside of a `form` tag

2023-10-31 16:43 UTC, shawnkost commented on html-forms/index.html
> +      <select>
The `id="dropdown"` needs to go on the `select`

2023-11-01 17:28 UTC, tran-christopher commented
![Animation](https://github.com/tran-christopher/c1023-code-solutions/assets/145728509/01ac932d-0f8b-4f17-9e3f-00d0627bd366)

2023-11-03 15:58 UTC, shawnkost approved these changes
👍🏻

2023-11-03 17:27 UTC, merged