css layout classes - Chris Tran
tran-christopher/c1023-code-solutions pull request #33
Opened 2023-11-02 03:05 UTC by tran-christopher

![Animation](https://github.com/tran-christopher/c1023-code-solutions/assets/145728509/ca358b9c-079c-4c3c-bdda-718a7fb2fd27)

2023-11-02 03:21 UTC, shawnkost requested changes
Couple changes here Chris!

2023-11-02 03:21 UTC, shawnkost commented on css-layout-classes/styles.css
> +}
Your `.container` shouldn't have any properties related to `flex` on here. This won't necessarily always be the case, but just for this specific exercise.

2023-11-02 03:21 UTC, shawnkost commented on css-layout-classes/styles.css
> +  justify-content: space-evenly;
Delete this, we aren't doing anything with `justify-content` here

2023-11-11 22:12 UTC, tran-christopher commented
![Animation ](https://github.com/tran-christopher/c1023-code-solutions/assets/145728509/9562b2c4-c74d-431a-b3eb-fdecbc4f80b2)

2023-12-13 18:17 UTC, shawnkost approved these changes
👍🏻

2023-12-17 01:32 UTC, merged